# File: push-merge.yml

name: Push_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - main
      - env-uat
      - env-prod
  paths:
    exclude:
      - /**/*.md
      - docs/*
      - .github/*
      - .gitignore

pr: none

resources:
  - repo: self

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: ./variables/global.yml
  - name: environment
    ${{ if eq(variables['Build.SourceBranchName'], 'env-prod') }}:
      value: "prod"
    ${{ elseif eq(variables['Build.SourceBranchName'], 'env-uat') }}:
      value: "uat"
    ${{ else }}:
      value: "dev"
  - template: ./variables/${{ variables.environment }}.yml
  - name: tf_apply
    value: true
  - name: helmsman_apply
    value: "--apply"

stages:
  - stage: Build
    displayName: Terraform Build
    jobs:
      - template: ./templates/infrastructure.yml
        parameters:
          TF_VERSION: ${{ variables.TF_VERSION }}
          TF_WORKSPACE_NAME: ${{ variables.environment }}
          TF_VAR_FILE: ${{ variables.tf_var_file }}
          TF_APPLY: ${{ variables.tf_apply }}
          AZ_SERVICE_CONNECTION: ${{ variables.AZ_SERVICE_CONNECTION }}
          TERRAFORM_DIRECTORY: ${{ variables.TERRAFORM_DIRECTORY }}

  - stage: Deploy
    displayName: Helmsman Deploy
    condition: succeeded()
    jobs:
      - template: ./templates/release.yml
        parameters:
          HELMSMAN_VERSION: ${{ variables.HELMSMAN_VERSION }}
          HELMSMAN_TOML_FILE: ${{ variables.helmsman_toml_file }}
          HELMSMAN_APPLY: ${{ variables.helmsman_apply }}
          HELMSMAN_WORKSPACE_NAME: ${{ variables.environment }}
          KUBERNETES_SERVICE_CONNECTION: ${{ variables.KUBERNETES_SERVICE_CONNECTION }}
          KUBERNETES_SERVICE_ACCOUNT: ${{ variables.KUBERNETES_SERVICE_ACCOUNT }}
          KUBERNETES_NAMESPACE: ${{ variables.KUBERNETES_NAMESPACE }}
          BUILD_ENV: "Build"