---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sonarqube-ext-dev
  name: helmsman
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      [
        "secrets",
        "configmaps",
        "services",
        "deployments",
        "ingresses",
        "serviceaccounts",
        "statefulsets",
      ]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmsman
rules:
  - apiGroups: [""]
    resources:
      [
        "configmaps",
        "endpoints",
        "nodes",
        "pods",
        "secrets",
      ]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: 
      [
        "nodes",
        "namespaces",
      ]
    verbs: ["get"]
  - apiGroups: ["", "networking.k8s.io"]
    resources:
      [
        "services",
        "ingresses",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["", "networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
  - apiGroups: ["", "networking.k8s.io", "admissionregistration.k8s.io"]
    resources: 
      [
        "ingressclasses", 
        "validatingwebhookconfigurations"
      ]
    verbs: ["get", "list", "create", "patch", "update", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch", "get"]
