---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helmsman
  namespace: sonarqube-ext-dev
subjects:
  - kind: ServiceAccount
    name: helmsman
    namespace: sonarqube-ext-dev
roleRef:
  kind: Role
  name: helmsman
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helmsman
subjects:
  - kind: ServiceAccount
    name: helmsman
    namespace: sonarqube-ext-dev
roleRef:
  kind: ClusterRole
  name: helmsman
  apiGroup: rbac.authorization.k8s.io
