variables:
  - name: AZ_SERVICE_CONNECTION
    value: "Corp-SonarQubeEnterprise-AppResources-DevTest"
  - name: KUBERNETES_SERVICE_CONNECTION
    value: "Corp-SonarQubeEnterprise-AKS-DevTest-sonarqube-ext-dev"
  - name: KUBERNETES_NAMESPACE
    value: "sonarqube-ext-dev"
  - name: TF_VAR_FILE
    value: "./environments/dev.auto.tfvars"
  - name: HELMSMAN_TOML_FILE
    value: "sonarqube.devtest.toml"
  - name: BUILD_ENV
    value: "BuildDevTest"
